/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package supershop;

import java.util.ArrayList;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import javax.swing.JTable;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 *
 * @author Shawon
 */
public class product extends javax.swing.JFrame {
    
   

    /**
     * Creates new form product
     */
    public product() {
        initComponents();
        
        
             
                item_show.removeAll();
                item_show.add(new_add);
                item_show.repaint();
                item_show.revalidate();
                
         ArrayList<product_list> list;
         list = Table_database.homePageContent();
        Object rowData[] = new Object[5];
        
        DefaultTableModel model =  (DefaultTableModel)homeTable.getModel();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        homeTable.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        homeTable.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
        homeTable.getColumnModel().getColumn(2).setCellRenderer( centerRenderer );
        homeTable.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );
        homeTable.getColumnModel().getColumn(4).setCellRenderer( centerRenderer );
   //     homeTable.getColumnModel().getColumn(5).setCellRenderer( centerRenderer );
   //     homeTable.getColumnModel().getColumn(6).setCellRenderer( centerRenderer );
        

       
        model.setRowCount(0); //To clear mobileTable
        
        for(int i=0; i<list.size(); i++){
            rowData[0] = list.get(i).getName();
            rowData[1] = list.get(i).getCatagory();
                  rowData[2] = list.get(i).getOriginal_price();
               rowData[3] = list.get(i).getSup_com();
            rowData[4] = list.get(i).getVat();
      
         
          //  rowData[5] = list.get(i).getSupp_company();
          //  rowData[6] = list.get(i).getDescription();
           // ImageIcon ii = new ImageIcon(getClass().getResource("/products/electronics/"+temp));
            ///=Image resizedImage = ii.getImage();
           // ii = new ImageIcon(resizedImage.getScaledInstance(160, 160, Image.SCALE_SMOOTH));
            
           // rowData[5] = ii;
            model.addRow(rowData);
            homeTable.setRowHeight(50);
            homeTable.getColumnModel().getColumn(4).setPreferredWidth(150);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        gro_but = new javax.swing.JButton();
        fru_veg_but = new javax.swing.JButton();
        fi_me_but = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        toi_but = new javax.swing.JButton();
        kid_but = new javax.swing.JButton();
        add_but = new javax.swing.JButton();
        offer_but = new javax.swing.JButton();
        jScrollPane9 = new javax.swing.JScrollPane();
        trolTable = new javax.swing.JTable();
        item_show = new javax.swing.JPanel();
        groceries = new javax.swing.JPanel();
        groTable = new javax.swing.JScrollPane();
        grocTable = new javax.swing.JTable();
        new_add = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        homeTable = new javax.swing.JTable();
        offer = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        offerTable = new javax.swing.JTable();
        fru_veg = new javax.swing.JPanel();
        jScrollPane7 = new javax.swing.JScrollPane();
        fru_vegTable = new javax.swing.JTable();
        Fi_me = new javax.swing.JPanel();
        jScrollPane8 = new javax.swing.JScrollPane();
        Fi_meTable = new javax.swing.JTable();
        troiletries = new javax.swing.JPanel();
        Kids = new javax.swing.JPanel();
        jScrollPane10 = new javax.swing.JScrollPane();
        kidstable = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(97, 212, 195));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/product_logo_icon.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 11, -1, -1));

        jLabel2.setFont(new java.awt.Font("Copperplate Gothic Bold", 1, 20)); // NOI18N
        jLabel2.setText("  Welcome  to  Collective Mart  Shopping");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(93, 19, 511, 39));

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/search-ico.png"))); // NOI18N
        jButton1.setPreferredSize(new java.awt.Dimension(40, 40));
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(940, 20, -1, -1));

        jTextField1.setText("Search anything");
        jTextField1.setPreferredSize(new java.awt.Dimension(210, 40));
        jTextField1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTextField1MouseClicked(evt);
            }
        });
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 20, -1, -1));

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1013, 71);

        jPanel2.setBackground(new java.awt.Color(0, 150, 120));

        gro_but.setBackground(new java.awt.Color(0, 150, 120));
        gro_but.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        gro_but.setText("Groceries");
        gro_but.setBorder(null);
        gro_but.setPreferredSize(new java.awt.Dimension(80, 30));
        gro_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gro_butActionPerformed(evt);
            }
        });

        fru_veg_but.setBackground(new java.awt.Color(0, 150, 120));
        fru_veg_but.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        fru_veg_but.setText("Fruits/Vegetables");
        fru_veg_but.setBorder(null);
        fru_veg_but.setPreferredSize(new java.awt.Dimension(135, 30));
        fru_veg_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fru_veg_butActionPerformed(evt);
            }
        });

        fi_me_but.setBackground(new java.awt.Color(0, 150, 120));
        fi_me_but.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        fi_me_but.setText("Fish/meat ");
        fi_me_but.setBorder(null);
        fi_me_but.setPreferredSize(new java.awt.Dimension(110, 30));
        fi_me_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fi_me_butActionPerformed(evt);
            }
        });

        jButton9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/cart.jpg"))); // NOI18N
        jButton9.setPreferredSize(new java.awt.Dimension(35, 30));

        jButton10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/face_ico.png"))); // NOI18N
        jButton10.setPreferredSize(new java.awt.Dimension(30, 30));
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        toi_but.setBackground(new java.awt.Color(0, 150, 120));
        toi_but.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        toi_but.setText("Toiletries");
        toi_but.setBorder(null);
        toi_but.setPreferredSize(new java.awt.Dimension(95, 30));
        toi_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toi_butActionPerformed(evt);
            }
        });

        kid_but.setBackground(new java.awt.Color(0, 150, 120));
        kid_but.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        kid_but.setText("Kid's Corner");
        kid_but.setBorder(null);
        kid_but.setPreferredSize(new java.awt.Dimension(120, 30));
        kid_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kid_butActionPerformed(evt);
            }
        });

        add_but.setBackground(new java.awt.Color(0, 150, 120));
        add_but.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        add_but.setText("Newly added");
        add_but.setBorder(null);
        add_but.setPreferredSize(new java.awt.Dimension(115, 30));
        add_but.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                add_butMouseClicked(evt);
            }
        });
        add_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                add_butActionPerformed(evt);
            }
        });

        offer_but.setBackground(new java.awt.Color(0, 150, 120));
        offer_but.setFont(new java.awt.Font("Century Gothic", 1, 12)); // NOI18N
        offer_but.setText("Offered item");
        offer_but.setBorder(null);
        offer_but.setPreferredSize(new java.awt.Dimension(105, 30));
        offer_but.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                offer_butActionPerformed(evt);
            }
        });

        trolTable.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        trolTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Brand Name", "Model", "Price", "Stock", "Features", "Photo"
            }
        ) {
            Class[] types = new Class[]{
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class,
                java.lang.Integer.class, java.lang.String.class, javax.swing.Icon.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }

            public Class getColumnClass(int columnIndex){
                return types [columnIndex];
            }

        });
        trolTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        trolTable.setSelectionBackground(new java.awt.Color(0, 150, 136));
        trolTable.getTableHeader().setReorderingAllowed(false);
        trolTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                trolTableMouseClicked(evt);
            }
        });
        jScrollPane9.setViewportView(trolTable);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(add_but, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(offer_but, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(gro_but, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fru_veg_but, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(fi_me_but, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(toi_but, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(kid_but, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 102, Short.MAX_VALUE)
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane9, javax.swing.GroupLayout.DEFAULT_SIZE, 911, Short.MAX_VALUE)
                        .addGap(79, 79, 79))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(fru_veg_but, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(gro_but, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(fi_me_but, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(toi_but, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(kid_but, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(add_but, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(offer_but, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane9, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(0, 70, 1000, 50);

        item_show.setLayout(new java.awt.CardLayout());

        grocTable.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        grocTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Product Name", "Price" , "Supplier Company", "VAT(%)"
            }
        ) {
            Class[] groc = new Class[]{
                java.lang.String.class,
                java.lang.Double.class,
                java.lang.String.class,
                java.lang.Double.class,
            };
            boolean[] canEdit = new boolean [] {
                false, false, false,false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }

            public Class getColumnClass(int columnIndex){
                return groc [columnIndex];
            }

        });
        grocTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        grocTable.setSelectionBackground(new java.awt.Color(0, 150, 136));
        grocTable.getTableHeader().setReorderingAllowed(false);
        grocTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                grocTableMouseClicked(evt);
            }
        });
        groTable.setViewportView(grocTable);

        javax.swing.GroupLayout groceriesLayout = new javax.swing.GroupLayout(groceries);
        groceries.setLayout(groceriesLayout);
        groceriesLayout.setHorizontalGroup(
            groceriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1008, Short.MAX_VALUE)
            .addGroup(groceriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(groceriesLayout.createSequentialGroup()
                    .addComponent(groTable, javax.swing.GroupLayout.PREFERRED_SIZE, 1008, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        groceriesLayout.setVerticalGroup(
            groceriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 440, Short.MAX_VALUE)
            .addGroup(groceriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(groceriesLayout.createSequentialGroup()
                    .addComponent(groTable, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 11, Short.MAX_VALUE)))
        );

        item_show.add(groceries, "card4");

        homeTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                " product Name", "Catagory", "Price", "Supplier Company" ,"Vat(%)"
            }
        ){
            Class[] shawon = new Class[]
            {
                java.lang.String.class,
                java.lang.String.class,
                java.lang.Double.class,
                java.lang.String.class,
                java.lang.Double.class,
            };
            boolean[] canchange = new boolean []{
                false,
                false,
                false,
                false,
                false
            };
            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canchange [columnIndex];
            }
            public Class getColumnClass(int columnIndex){
                return shawon [columnIndex];
            }
        }
    );
    homeTable.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            homeTableMouseClicked(evt);
        }
    });
    jScrollPane1.setViewportView(homeTable);

    javax.swing.GroupLayout new_addLayout = new javax.swing.GroupLayout(new_add);
    new_add.setLayout(new_addLayout);
    new_addLayout.setHorizontalGroup(
        new_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
    );
    new_addLayout.setVerticalGroup(
        new_addLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
    );

    item_show.add(new_add, "card2");

    offerTable.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
    offerTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Brand Name", "Model", "Price", "Stock", "Features", "Photo"
        }
    ) {
        Class[] types = new Class[]{
            java.lang.String.class, java.lang.String.class, java.lang.Integer.class,
            java.lang.Integer.class, java.lang.String.class, javax.swing.Icon.class
        };
        boolean[] canEdit = new boolean [] {
            false, false, false, false, false, false
        };

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }

        public Class getColumnClass(int columnIndex){
            return types [columnIndex];
        }

    });
    offerTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    offerTable.setSelectionBackground(new java.awt.Color(0, 150, 136));
    offerTable.getTableHeader().setReorderingAllowed(false);
    offerTable.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            offerTableMouseClicked(evt);
        }
    });
    jScrollPane6.setViewportView(offerTable);

    javax.swing.GroupLayout offerLayout = new javax.swing.GroupLayout(offer);
    offer.setLayout(offerLayout);
    offerLayout.setHorizontalGroup(
        offerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
    );
    offerLayout.setVerticalGroup(
        offerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
    );

    item_show.add(offer, "card3");

    fru_vegTable.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
    fru_vegTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Brand Name", "Model", "Price", "Stock", "Features", "Photo"
        }
    ) {
        Class[] types = new Class[]{
            java.lang.String.class, java.lang.String.class, java.lang.Integer.class,
            java.lang.Integer.class, java.lang.String.class, javax.swing.Icon.class
        };
        boolean[] canEdit = new boolean [] {
            false, false, false, false, false, false
        };

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }

        public Class getColumnClass(int columnIndex){
            return types [columnIndex];
        }

    });
    fru_vegTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    fru_vegTable.setSelectionBackground(new java.awt.Color(0, 150, 136));
    fru_vegTable.getTableHeader().setReorderingAllowed(false);
    fru_vegTable.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            fru_vegTableMouseClicked(evt);
        }
    });
    jScrollPane7.setViewportView(fru_vegTable);

    javax.swing.GroupLayout fru_vegLayout = new javax.swing.GroupLayout(fru_veg);
    fru_veg.setLayout(fru_vegLayout);
    fru_vegLayout.setHorizontalGroup(
        fru_vegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
    );
    fru_vegLayout.setVerticalGroup(
        fru_vegLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane7, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
    );

    item_show.add(fru_veg, "card5");

    Fi_meTable.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
    Fi_meTable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Brand Name", "Model", "Price", "Stock", "Features", "Photo"
        }
    ) {
        Class[] types = new Class[]{
            java.lang.String.class, java.lang.String.class, java.lang.Integer.class,
            java.lang.Integer.class, java.lang.String.class, javax.swing.Icon.class
        };
        boolean[] canEdit = new boolean [] {
            false, false, false, false, false, false
        };

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }

        public Class getColumnClass(int columnIndex){
            return types [columnIndex];
        }

    });
    Fi_meTable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    Fi_meTable.setSelectionBackground(new java.awt.Color(0, 150, 136));
    Fi_meTable.getTableHeader().setReorderingAllowed(false);
    Fi_meTable.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            Fi_meTableMouseClicked(evt);
        }
    });
    jScrollPane8.setViewportView(Fi_meTable);

    javax.swing.GroupLayout Fi_meLayout = new javax.swing.GroupLayout(Fi_me);
    Fi_me.setLayout(Fi_meLayout);
    Fi_meLayout.setHorizontalGroup(
        Fi_meLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
    );
    Fi_meLayout.setVerticalGroup(
        Fi_meLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane8, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
    );

    item_show.add(Fi_me, "card5");

    javax.swing.GroupLayout troiletriesLayout = new javax.swing.GroupLayout(troiletries);
    troiletries.setLayout(troiletriesLayout);
    troiletriesLayout.setHorizontalGroup(
        troiletriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 1000, Short.MAX_VALUE)
    );
    troiletriesLayout.setVerticalGroup(
        troiletriesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGap(0, 440, Short.MAX_VALUE)
    );

    item_show.add(troiletries, "card5");

    kidstable.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
    kidstable.setModel(new javax.swing.table.DefaultTableModel(
        new Object [][] {

        },
        new String [] {
            "Brand Name", "Model", "Price", "Stock", "Features", "Photo"
        }
    ) {
        Class[] types = new Class[]{
            java.lang.String.class, java.lang.String.class, java.lang.Integer.class,
            java.lang.Integer.class, java.lang.String.class, javax.swing.Icon.class
        };
        boolean[] canEdit = new boolean [] {
            false, false, false, false, false, false
        };

        public boolean isCellEditable(int rowIndex, int columnIndex) {
            return canEdit [columnIndex];
        }

        public Class getColumnClass(int columnIndex){
            return types [columnIndex];
        }

    });
    kidstable.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
    kidstable.setSelectionBackground(new java.awt.Color(0, 150, 136));
    kidstable.getTableHeader().setReorderingAllowed(false);
    kidstable.addMouseListener(new java.awt.event.MouseAdapter() {
        public void mouseClicked(java.awt.event.MouseEvent evt) {
            kidstableMouseClicked(evt);
        }
    });
    jScrollPane10.setViewportView(kidstable);

    javax.swing.GroupLayout KidsLayout = new javax.swing.GroupLayout(Kids);
    Kids.setLayout(KidsLayout);
    KidsLayout.setHorizontalGroup(
        KidsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1000, Short.MAX_VALUE)
    );
    KidsLayout.setVerticalGroup(
        KidsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addComponent(jScrollPane10, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
    );

    item_show.add(Kids, "card4");

    getContentPane().add(item_show);
    item_show.setBounds(0, 120, 1000, 440);

    setSize(new java.awt.Dimension(1016, 600));
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTextField1MouseClicked
        jTextField1.setText("");
    }//GEN-LAST:event_jTextField1MouseClicked

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
         new SignIn_up().setVisible(true);
                this.setVisible(false);
    }//GEN-LAST:event_jButton10ActionPerformed

    private void add_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_add_butActionPerformed
               
                item_show.removeAll();
                item_show.add(new_add);
                item_show.repaint();
                item_show.revalidate();
                
         ArrayList<product_list> list;
         list = Table_database.homePageContent();
        Object rowData[] = new Object[5];
        
        DefaultTableModel model =  (DefaultTableModel)homeTable.getModel();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        homeTable.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        homeTable.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
        homeTable.getColumnModel().getColumn(2).setCellRenderer( centerRenderer );
        homeTable.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );
        homeTable.getColumnModel().getColumn(4).setCellRenderer( centerRenderer );
   //     homeTable.getColumnModel().getColumn(5).setCellRenderer( centerRenderer );
   //     homeTable.getColumnModel().getColumn(6).setCellRenderer( centerRenderer );
        

       
        model.setRowCount(0); //To clear mobileTable
        
        for(int i=0; i<list.size(); i++){
            rowData[0] = list.get(i).getName();
            rowData[1] = list.get(i).getCatagory();
            rowData[2] = list.get(i).getOriginal_price();
            rowData[3] = list.get(i).getSup_com();
            rowData[4] = list.get(i).getVat();
          
        
          //  rowData[5] = list.get(i).getSupp_company();
          //  rowData[6] = list.get(i).getDescription();
           // ImageIcon ii = new ImageIcon(getClass().getResource("/products/electronics/"+temp));
            ///=Image resizedImage = ii.getImage();
           // ii = new ImageIcon(resizedImage.getScaledInstance(160, 160, Image.SCALE_SMOOTH));
            
           // rowData[5] = ii;
            model.addRow(rowData);
            homeTable.setRowHeight(50);
            homeTable.getColumnModel().getColumn(4).setPreferredWidth(50);
        }
    }//GEN-LAST:event_add_butActionPerformed

    private void offer_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_offer_butActionPerformed
              
    }//GEN-LAST:event_offer_butActionPerformed

    private void offerTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_offerTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_offerTableMouseClicked

    private void fru_vegTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_fru_vegTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_fru_vegTableMouseClicked

    private void Fi_meTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Fi_meTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_Fi_meTableMouseClicked

    private void trolTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_trolTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_trolTableMouseClicked

    private void kidstableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_kidstableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_kidstableMouseClicked

    private void grocTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_grocTableMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_grocTableMouseClicked
    product_details pi = new product_details();
    private void add_butMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_add_butMouseClicked
        
    }//GEN-LAST:event_add_butMouseClicked

    private void homeTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeTableMouseClicked
        pi.setVisible(true);
        pi.pack();
        int selectedRow = homeTable.getSelectedRow();
        TableModel tm = homeTable.getModel();
        
        String name = tm.getValueAt(selectedRow, 0).toString();
        String catagory = tm.getValueAt(selectedRow, 1).toString();
        String vat = tm.getValueAt(selectedRow, 2).toString();
        String o_price = tm.getValueAt(selectedRow, 3).toString();
        String p_price = tm.getValueAt(selectedRow, 4).toString();
        
        pi.name_lvl.setText(name);
        pi.cat_lvl.setText(catagory);
        pi.vat_lvl.setText(vat);
        pi.discount_lvl.setText("No discount");
        pi.stock_lvl.setText("56");
        pi.price_lvl.setText(o_price);
    }//GEN-LAST:event_homeTableMouseClicked

    private void gro_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_gro_butActionPerformed
          
                item_show.removeAll();
                item_show.add(groceries);
                item_show.repaint();
                item_show.revalidate();
                
         ArrayList<groc_list> list;
         list = Table_database.grocContent();
        Object rowData[] = new Object[4];
        
        DefaultTableModel model =  (DefaultTableModel)grocTable.getModel();
        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment( JLabel.CENTER );
        grocTable.getColumnModel().getColumn(0).setCellRenderer( centerRenderer );
        grocTable.getColumnModel().getColumn(1).setCellRenderer( centerRenderer );
        grocTable.getColumnModel().getColumn(2).setCellRenderer( centerRenderer );
        grocTable.getColumnModel().getColumn(3).setCellRenderer( centerRenderer );
       
   //     homeTable.getColumnModel().getColumn(5).setCellRenderer( centerRenderer );
   //     homeTable.getColumnModel().getColumn(6).setCellRenderer( centerRenderer );
        

       
        model.setRowCount(0); //To clear mobileTable
        
        for(int i=0; i<list.size(); i++){
            rowData[0] = list.get(i).getName();
            rowData[1] = list.get(i).getOriginal_price();
            rowData[2] = list.get(i).getSup_com();
            rowData[3] = list.get(i).getVat();
          
        
          //  rowData[5] = list.get(i).getSupp_company();
          //  rowData[6] = list.get(i).getDescription();
           // ImageIcon ii = new ImageIcon(getClass().getResource("/products/electronics/"+temp));
            ///=Image resizedImage = ii.getImage();
           // ii = new ImageIcon(resizedImage.getScaledInstance(160, 160, Image.SCALE_SMOOTH));
            
           // rowData[5] = ii;
            model.addRow(rowData);
            grocTable.setRowHeight(50);
            grocTable.getColumnModel().getColumn(3).setPreferredWidth(50);
        }      // TODO add your handling code here:
    }//GEN-LAST:event_gro_butActionPerformed

    private void fru_veg_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fru_veg_butActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fru_veg_butActionPerformed

    private void fi_me_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fi_me_butActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fi_me_butActionPerformed

    private void toi_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toi_butActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toi_butActionPerformed

    private void kid_butActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kid_butActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kid_butActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(product.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new product().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Fi_me;
    private javax.swing.JTable Fi_meTable;
    private javax.swing.JPanel Kids;
    private javax.swing.JButton add_but;
    private javax.swing.JButton fi_me_but;
    private javax.swing.JPanel fru_veg;
    private javax.swing.JTable fru_vegTable;
    private javax.swing.JButton fru_veg_but;
    private javax.swing.JScrollPane groTable;
    private javax.swing.JButton gro_but;
    private javax.swing.JTable grocTable;
    private javax.swing.JPanel groceries;
    private javax.swing.JTable homeTable;
    private javax.swing.JPanel item_show;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane10;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JScrollPane jScrollPane9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JButton kid_but;
    private javax.swing.JTable kidstable;
    private javax.swing.JPanel new_add;
    private javax.swing.JPanel offer;
    private javax.swing.JTable offerTable;
    private javax.swing.JButton offer_but;
    private javax.swing.JButton toi_but;
    private javax.swing.JPanel troiletries;
    private javax.swing.JTable trolTable;
    // End of variables declaration//GEN-END:variables
}
